<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyVersion>1.2.2</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackupCSLib\BackupCSLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="common">
      <HintPath>..\..\common-cs\common\bin\Release\net9.0-windows\common.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
