<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyVersion>1.2.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackupCSLib\BackupCSLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="common">
      <HintPath>..\..\common-cs\common\bin\Release\net9.0-windows\common.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
