<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="common">
      <HintPath>..\..\common-cs\common\bin\Release\net10.0-windows\common.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
